<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/isotope.js"></script>
<script src="js/imagesloaded.min.js"></script>
<script src="js/wow.min.js"></script>
<script src="js/custom.js"></script>
<script src="js/modernizr.custom.js"></script>
<script src="js/waypoint.js"></script>
<!-- <script src="js/stuck.js"></script> -->